from typing import Protocol
from .contracts import DoctorReport, SecurityIdentity, WatchlistView
from trading_platform.domain.data import SyncRequest, SyncResult
from trading_platform.domain.workflow import ArtifactManifestView, ResearchWorkflowRequest, ResearchWorkflowResult, WorkflowHistory

class PlatformPersistence(Protocol):
    def add_watchlist_item(self, invocation_id: str, security: SecurityIdentity) -> WatchlistView: ...
    def list_watchlist_items(self) -> tuple[WatchlistView, ...]: ...
    def doctor(self) -> DoctorReport: ...


class DataSyncPort(Protocol):
    def sync(self, request: SyncRequest) -> SyncResult: ...


class ResearchWorkflowPort(Protocol):
    def run(self, request: ResearchWorkflowRequest) -> ResearchWorkflowResult: ...
    def get_history(self, workflow_run_id: str) -> WorkflowHistory: ...
    def get_manifest(self, manifest_id: str) -> ArtifactManifestView: ...
