from typing import Protocol
from .contracts import CancelWorkflowCommand, DoctorReport, ResumeWorkflowCommand, SecurityIdentity, WatchlistView
from trading_platform.domain.data import ProviderAttemptEvidence, SyncRequest, SyncResult
from trading_platform.domain.workflow import ArtifactManifestView, ResearchArtifactView, ResearchWorkflowRequest, ResearchWorkflowResult, WorkflowHistory
from trading_platform.domain.chart import AnnotationCommand, AnnotationVersion, ChartSeries, CoordinateMigration, CoordinateMigrationResult
from trading_platform.domain.plans import ActivatePlanVersionCommand, ActivePlanView, ChangePlanLifecycleCommand, ConfirmPlanDraftCommand, CreatePlanDraftCommand, DiscardPlanDraftCommand, PlanConfirmationView, TradePlanDraftView, TradePlanVersionView, UpdatePlanDraftCommand
from trading_platform.application.market_contracts import BuildMarketSnapshotCommand, EvaluatePlanCommand
from trading_platform.domain.market import MarketSnapshotView, PlanEvaluationView

class PlatformPersistence(Protocol):
    def add_watchlist_item(self, invocation_id: str, security: SecurityIdentity) -> WatchlistView: ...
    def list_watchlist_items(self) -> tuple[WatchlistView, ...]: ...
    def doctor(self) -> DoctorReport: ...


class DataSyncPort(Protocol):
    def sync(self, request: SyncRequest) -> SyncResult: ...
    def snapshot_members(self, snapshot_id: str): ...
    def provider_attempt_evidence(self, attempt_ids: tuple[str, ...]) -> tuple[ProviderAttemptEvidence, ...]: ...


class AccountPort(Protocol):
    def get_detail(self, account_id: str): ...


class ResearchWorkflowPort(Protocol):
    def run(self, request: ResearchWorkflowRequest) -> ResearchWorkflowResult: ...
    def get_history(self, workflow_run_id: str) -> WorkflowHistory: ...
    def get_manifest(self, manifest_id: str) -> ArtifactManifestView: ...
    def get_research_artifact(self, artifact_record_id: str) -> ResearchArtifactView: ...
    def resume(self, command: ResumeWorkflowCommand) -> ResearchWorkflowResult: ...
    def cancel(self, command: CancelWorkflowCommand) -> None: ...


class ChartPort(Protocol):
    def get_series(self, security_id: str, snapshot_id: str, interval: str = "1d", adjustment_mode: str = "none", factor_snapshot_id: str | None = None) -> ChartSeries: ...
    def create(self, command: AnnotationCommand) -> AnnotationVersion: ...
    def revise(self, command: AnnotationCommand) -> AnnotationVersion: ...
    def delete(self, command: AnnotationCommand) -> AnnotationVersion: ...
    def restore(self, command: AnnotationCommand) -> AnnotationVersion: ...
    def migrate(self, command: CoordinateMigration) -> CoordinateMigrationResult: ...
    def get_history(self, annotation_id: str) -> tuple[AnnotationVersion, ...]: ...
    def list_history(self, security_id: str) -> tuple[AnnotationVersion, ...]: ...


class PlanPort(Protocol):
    def create_draft(self, command: CreatePlanDraftCommand) -> TradePlanDraftView: ...
    def update_draft(self, command: UpdatePlanDraftCommand) -> TradePlanDraftView: ...
    def discard_draft(self, command: DiscardPlanDraftCommand) -> TradePlanDraftView: ...
    def confirm_draft(self, command: ConfirmPlanDraftCommand) -> TradePlanVersionView: ...
    def activate_version(self, command: ActivatePlanVersionCommand) -> TradePlanVersionView: ...
    def deactivate(self, command: ChangePlanLifecycleCommand) -> ActivePlanView: ...
    def end(self, command: ChangePlanLifecycleCommand) -> ActivePlanView: ...
    def get_draft(self, draft_id: str) -> TradePlanDraftView: ...
    def get_version(self, version_id: str) -> TradePlanVersionView: ...
    def get_active_for_security(self, security_id: str) -> ActivePlanView: ...
    def get_lifecycle(self, plan_id: str) -> ActivePlanView: ...
    def confirmation(self, draft_id: str) -> PlanConfirmationView: ...


class MarketPort(Protocol):
    def build_market_snapshot(self, command: BuildMarketSnapshotCommand) -> MarketSnapshotView: ...
    def evaluate_plan(self, command: EvaluatePlanCommand) -> PlanEvaluationView: ...
    def get_market_snapshot(self, market_snapshot_id: str) -> MarketSnapshotView: ...
    def get_plan_evaluation(self, evaluation_id: str) -> PlanEvaluationView: ...


class WorkspacePort(Protocol):
    def build(self, security_id: str, snapshot_id: str): ...
    def authorize_update(self, invocation_id: str, security_id: str, requested_date: str, effective_session_date: str): ...
