from typing import Protocol
from .contracts import DoctorReport, SecurityIdentity, WatchlistView

class PlatformPersistence(Protocol):
    def add_watchlist_item(self, invocation_id: str, security: SecurityIdentity) -> WatchlistView: ...
    def list_watchlist_items(self) -> tuple[WatchlistView, ...]: ...
    def doctor(self) -> DoctorReport: ...
